merge_protections:
  - name: Login
    description: |-
      
      Fastboot oem unlock 
    if:
      - "#base ="
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))\
        ?:"
